CXX = c++

CPPFLAGS = -Wall -Wextra -Werror --std=c++98

SRC1 = part1.cpp
SRC2 = part2.cpp

PART1 = part1
PART2 = part2

$(PART1):
	$(CXX) $(CPPFLAGS) $(SRC1)

$(PART2):
	$(CXX) $(CPPFLAGS) $(SRC2)

fclean:
	rm -f a.out
